runtime: python311

handlers:
# file with extensions (longer cache period)
- url: /(.*\.(css|woff|woff2|ico|png|jpg|map|zip))
  static_files: static/\1
  upload: static/(.*)
  expiration: "14d"
  secure: always
  http_headers:
    Cross-Origin-Opener-Policy: "same-origin"
    Cross-Origin-Embedder-Policy: "require-corp"
    Cross-Origin-Resource-Policy: "cross-origin"

# file with defined extensions
- url: /(.*\.(html|txt|js|py|csv|svg|toml|json))
  static_files: static/\1
  upload: static/(.*)
  secure: always
  http_headers:
    Cross-Origin-Opener-Policy: "same-origin"
    Cross-Origin-Embedder-Policy: "require-corp"
    Cross-Origin-Resource-Policy: "cross-origin"

# assume file without extensions use index.html
- url: /(.*)/
  static_files: static/\1/index.html
  upload: static/(.*)/index.html
  secure: always
  http_headers:
    Cross-Origin-Opener-Policy: "same-origin"
    Cross-Origin-Embedder-Policy: "require-corp"
    Cross-Origin-Resource-Policy: "cross-origin"

- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always
  http_headers:
    Cross-Origin-Opener-Policy: "same-origin"
    Cross-Origin-Embedder-Policy: "require-corp"
    Cross-Origin-Resource-Policy: "cross-origin"

- url: /.*
  script: auto